security:
    session_fixation_strategy: none

    access_decision_manager:
        strategy: affirmative

    acl:
        connection: default

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User:
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

    providers:
        sulu:
            id: sulu_security.user_provider

    access_control:
        - { path: l91_sulu_website_user.profile, roles: ROLE_USER }

    firewalls:
        website:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: l91_sulu_website_user.login
                check_path: l91_sulu_website_user.login_check
            logout:
                path: l91_sulu_website_user.logout
                target: l91_sulu_website_user.login

sulu_security:
    checker:
        enabled: true
